<?php


namespace App\Service;


use KnpU\LoremIpsumBundle\KnpWordProvider;

class CustomWordProvider extends KnpWordProvider
{
    public function getWordList(): array
    {
        $words = parent::getWordList(); // TODO: Change the autogenerated stub
        $words[] = 'beach';

        return $words;
    }

}