<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nexy_slack.client' shared service.

include_once $this->targetDirs[3].'/vendor/nexylan/slack/src/Client.php';

return $this->services['nexy_slack.client'] = new \Nexy\Slack\Client($this->getEnv('string:SLACK_WEBHOOK_ENDPOINT'), $this->parameters['nexy_slack.config'], ($this->services['httplug.client'] ?? $this->load(__DIR__.'/getHttplug_ClientService.php')));
