<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knpu_lorem_ipsum.knpu_ipsum' shared service.

include_once $this->targetDirs[3].'/lib/LoremIpsumBundle/src/KnpUIpsum.php';

return $this->services['knpu_lorem_ipsum.knpu_ipsum'] = new \KnpU\LoremIpsumBundle\KnpUIpsum();
