<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeyr1o9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeyr1o9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUeyr1o9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUeyr1o9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUeyr1o9\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ueyr1o9',
    'container.build_id' => '769d7841',
    'container.build_time' => 1578489703,
));
